name: My First GitHub Action

on:
  push:

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Welcome to DevOps"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la
